services:
  web:
    build: .
    command: >
      sh -c './wait-for-it.sh db:5432 && alembic upgrade head && 
      python core/cmds.py loaddata && uvicorn src.main:app --host 0.0.0.0 --port 8000'
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:7.0.5-alpine
    restart: always
    env_file:
      - .env

volumes:
  db:
