"""Reviews

Revision ID: 005c0e95d23f
Revises: b44d4f071d44
Create Date: 2023-10-29 01:12:29.569829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "005c0e95d23f"
down_revision: Union[str, None] = "b44d4f071d44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_review",
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_foreign_key(
        None, "portals_portal", "users_user", ["admin_id"], ["id"], use_alter=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "portals_portal", type_="foreignkey")
    op.drop_table("users_review")
    # ### end Alembic commands ###
