"""Test

Revision ID: 8a0b3695b986
Revises:
Create Date: 2023-10-28 19:53:56.115456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a0b3695b986"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portals_portal",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("inn", sa.String(), nullable=False),
        sa.Column("main_hex_color", sa.String(), nullable=True),
        sa.Column("admin_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["admin_id"], ["users_user.id"], use_alter=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "portals_department",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("portal_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["portal_id"],
            ["portals_portal.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users_user",
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("patronymic", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("birth_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "role", sa.Enum("WORKER", "ADMIN", "SUPERUSER", "HR", name="role"), nullable=False
        ),
        sa.Column("is_dismissed", sa.Boolean(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=True),
        sa.Column("portal_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["portals_department.id"],
        ),
        sa.ForeignKeyConstraint(
            ["portal_id"],
            ["portals_portal.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_users_user_created_at"), "users_user", ["created_at"], unique=False)
    op.create_table(
        "courses_course",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("department_name", sa.String(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["department_name"],
            ["portals_department.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "courses_test",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("department_name", sa.String(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["department_name"],
            ["portals_department.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "portals_company",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "portals_user_department",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["portals_department.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "courses_user_course",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses_course.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "courses_user_test",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("test_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["test_id"],
            ["courses_test.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("courses_user_test")
    op.drop_table("courses_user_course")
    op.drop_table("portals_user_department")
    op.drop_table("portals_company")
    op.drop_table("courses_test")
    op.drop_table("courses_course")
    op.drop_index(op.f("ix_users_user_created_at"), table_name="users_user")
    op.drop_table("users_user")
    op.drop_table("portals_department")
    op.drop_table("portals_portal")
    # ### end Alembic commands ###
